name: H_jiny
title: H_jiny's portfolio
description: Jekflix is a template for Jekyll inspired by Netflix and made by Thiago Rossener.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
email: hwalan0411@gmail.com
disqus_username: disqus_username
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about   
  - title: Portfolio
    url: /portfolio
  - title: Contact
    url: /contact
